linguagens = ["Inglês", "Português", "Português", "Português", "Japonês", "Coreano", "Italiano", "Espanhol"]
print(linguagens)
print(f"Len: {len(linguagens)}")
print(f"Count de português: {linguagens.count('Português')}")
linguagens.reverse()
print(f"Reverse: {linguagens}")
linguagens.sort()
print(f"Sort: {linguagens}")
linguagens.sort(reverse=True)
print(f"Sort reverse True: {linguagens}")